name: Add comment
on:
  pull_request_target:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'TEAM1'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh pr comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This PR touched files owned by @idtag
