name: Add comment
on:
  pull_request_target:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'TEAM1'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - uses: actions/checkout@v4
      - id: comment-TEAM1
        run: gh pr comment --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: >
            This issue is available for anyone to work on.
