---
name: Labeled

on:
  pull_request:
    types:
      - labeled

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Notify
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mapping: >
            - label: TEAM1
              message: 'Hey, assess components were touched!'
              recipients:
                - '@idtag'
