# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    if: ${{!github.event.pull_request.draft}}
    steps:
      - id: label-PR
        name: 'Label PR'
        uses: actions/labeler@v5
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Comment PR'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ vars.DARKO }} owns this TEAM1!'
            })
