name: CI

on:
  pull_request:
    types:
      - labeled
  issue_comment:
    types:
      - created

jobs:
  label1:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        pull-requests: write

    steps:
      - id: label-PR
        name: 'Label PR'
        uses: actions/labeler@v5
