# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - id: label-PR
        uses: actions/labeler@v5
      - uses: actions/checkout@v4
      - id: comment-TEAM1
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@idtag owns this joint!'
            })
      
  # comment:
  #   runs-on: ubuntu-latest
  #   needs: label
  #   permissions:
  #     contents: read
  #     pull-requests: write
      
  #   steps:
  #     - id: comment-TEAM1
  #       if: contains(needs.jobs.label.outputs.new-labels, 'TEAM1')
  #       run: gh pr comment "$NUMBER" --body "$BODY"
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GH_REPO: ${{ github.repository }}
  #         NUMBER: ${{ github.event.pr.number }}
  #         BODY: >
  #           This issue is available for anyone to work on.
